server:
  port: 8081

spring:
  application:
    name: grpc-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}/${DB_NAME:}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 200
    open-in-view: false

grpc:
  client:
    default:
      address: static://localhost:9090
      negotiationType: PLAINTEXT
    test:
      address: static://localhost:9090
      negotiationType: PLAINTEXT
  server:
    enabled: false  # ?? ??? ????

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000